---
title: Example EventMAE Setup
execute:
    message: false
    warning: false
---

```{r}
library(MultiAssayExperiment)
library(SummarizedExperiment)
library(tidyverse)
library(fs)
library(here)

set.seed(202605)
data_dir <- here() / path("data")
src_dir  <- here() / path("src/data")
tmp <- dir_map(src_dir, source, type = "file")
```

## Load the toy MAE

```{r}
example_mae <- readRDS(data_dir / "example_mae.rds")
emae <- from_mae(example_mae)
events(emae)
```

## `view` options

```{r}
v_last <- view(emae, t_star = 25, strategy = "last")
v_all <- view(emae, t_star = Inf, strategy = "all")
v_last
```

## `life_table` options

```{r}
lt_visits <- life_table(emae, cut_strategy = "visits")
lt_visits
```

```{r}
lt_events <- life_table(emae, cut_strategy = "event_times")
lt_events
```

## Subsetting

```{r}
small <- emae |>
  subset_cohorts(c("C01", "C02")) |>
  subset_subjects(paste0("S00", sprintf("%02d", 1:10)))

samples(small)
events(small)
```

## Model Matrix

```{r}
design <- model_frame(emae, t_star = 28, strategy = "last")
design
```
